Added possibility to use CDATA sections in XML files
shrinkwrap/descriptors pull request #108
Opened 2017-01-25 19:35 UTC by tobiasstadler

2017-01-26 05:49 UTC, lordofthejars commented
Thank you very much for your contribution, looks good to me, let's wait for @bartoszmajsak review as well and we merge it.

2017-05-25 17:49 UTC, tobiasstadler commented
Any chance for getting this in?

2017-05-25 18:22 UTC, lordofthejars commented
Tomorrow morning I ll take a look

El 25 may. 2017 7:49 p. m., "Tobias Stadler" <notifications@github.com>
escribió:

> Any chance for getting this in?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/shrinkwrap/descriptors/pull/108#issuecomment-304076142>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABcmYZDgKDKZ3SUH9OIl-Xkcnh1iw7Ilks5r9b8ogaJpZM4Lt50e>
> .
>

2017-05-25 21:09 UTC, bartoszmajsak commented
Thanks for your contributions. Would you share some use cases when this is useful? We could use it then in the blog post announcement.

2017-05-25 21:11 UTC, bartoszmajsak requested changes
Just small thing, thanks again!

2017-05-25 21:11 UTC, bartoszmajsak commented on spi/src/main/java/org/jboss/shrinkwrap/descriptor/spi/node/Node.java
> +        // Cannot have children
Both comments in this method are not really needed for my taste as the code is self explanatory. Can you remove those?

2017-05-31 19:16 UTC, tobiasstadler commented
In my case the CDATA-section prevents my IDEs code formatting from screwing up the yams configuration

2017-06-01 16:19 UTC, bartoszmajsak approved these changes

2017-06-01 16:22 UTC, merged

2017-06-01 16:25 UTC, bartoszmajsak commented
Thank you for your contribution @tobiasstadler!